### PR TITLE
Modifications for sonarcloud

### PR DESCRIPTION
**Pull request by HannoSpreeuw**
This is for adding the Sonarcloud badge to the README.
And for issue #39 . 
By excluding a file generated by the Makefile we remove dozens of false positives.

### CODE REVIEW

**Comment by sverhoeven** [comment]
Analysis seems to work for *.py, *.js and *.html files, but not for *.hpp *.cpp files.

Could you investigate why for example `src/newtonraphson.hpp` is missing on https://sonarcloud.io/code?id=NLESC-JCER_cpp2wasm&selected=NLESC-JCER_cpp2wasm%3Asrc ?

**Comment by HannoSpreeuw** [comment]
@sverhoeven That is indeed weird. 
I could not yet find a Sonarcloud setting that excludes those files.
I could add the .cpp files and .hpp files to the .sonarcloud.properties file, so to the sonar.inclusions field, but that is perhaps not the most elegant solution.

**Comment by HannoSpreeuw** [comment]
image

This does not seem to make a difference

**Comment by sverhoeven** [comment]
Maybe it is a problem with the automatic analysis.
Can you try running the [scanner](https://sonarcloud.io/documentation/analysis/scan/sonarscanner/) locally?

**Comment by sverhoeven** [comment]
Let us fix C++ analysis to https://github.com/NLESC-JCER/cpp2wasm/issues/73

**Pull request merged**
