### PR TITLE
added citation metadata

### PR DESCRIPTION
**Pull request by jspaaks**
This PR adds CITATION.cff and .zenodo.json based on current contributors.

Refs #40

### CODE REVIEW

**Comment by sverhoeven** [comment]
CI Job failed due to bad release of Celery v4.4.4 see https://github.com/celery/celery/issues/6145, wait for v4.4.5 to restart failed jobs.

**Comment by sverhoeven** [comment]
After merge can you check some checkboxes in #40?

**Comment by jspaaks** [comment]
> After merge can you check some checkboxes in #40?

Done.

Are you making a release? I took the liberty of updating the date in CITATION.cff to today.

**Comment by sverhoeven** [comment]
Yes, I will make a release today, will need to write up CHANGELOG first though.

**Pull request merged**
